import'./menu.js';
import'./hero-swiper.js';
import './programs-swiper.js';
import './news-swiper.js';
import './faq.js';
import './reviews.js';
import './select.js';
import './modal.js';
import './valid-form.js';
import './popup-validate.js';
